schema:
  - 'src/graphql/schema.gql'
generates:
  src/graphql/generated/index.ts:
    documents:
      - 'src/**/*.graphql'
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-query'
    config:
      fetcher:
        func: '../graphql-fetcher#fetchData'
        isReactHook: false
