schema: src/graphql/schema.gql
generates:
  src/graphql/generated/graphql.ts:
    documents: 'src/**/*.graphql'
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-query'
    config:
      func: '../graphql-fetcher@fetchData'
      isReactHook: false
