# Change 'wenix-api' to your project name

version: '3.5'

volumes:
  postgres-data:
    driver: local

services:
  postgres:
    container_name: wenix-api-postgres
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=pass_secret
      - POSTGRES_DB=wenix-api-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

